config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/profile', to: 'pages#profile'

  resources :hostels, except: :new do
    resources :rooms, only: :create
    resources :reviews, only: :create
    resources :amenity_tags, only: :create
  end

  resources :rooms, only: %i[update destroy] do
    resources :reservations, only: :create
  end

  resources :amenity_tags, only: :destroy

  resources :reservations, only: %i[update destroy]
end

app/views/pages/home.html.erb
<div class="hostels-container">

  <% @hostels.each do |hostel| %>
    <div class="hostel-container" >
      <div class="image-container">
          <% if hostel.photos.attached? %>
            <%= cl_image_tag hostel.photos.last.key, class:"home-photo",crop: :fill %>
          <% end %>
      </div>
      <div class="info-container">
        <%= link_to "#{hostel.name}", hostel_path(hostel), class:"hostel-name" %> <br>
        <%= hostel.city %>
      </div>
    </div>
  <% end %>
</div>

<%# <h1 class="where-to-container">Where To Next...</h1> %>
<div class="cities">
  <div class="city">
    <img src="https://i.natgeofe.com/n/6fe32bbb-d989-4ff2-942c-a81ba0734680/bc0039_190107_04085-edit-edit_3x2.jpg" alt="cape town">
    <div class='text'>
      <a href="/?query=Cape+Town&button="><h3>cape town</h3></a>
    </div>
  </div>
  <div class="city">
    <img src="https://static.nationalgeographic.co.uk/files/styles/image_3200/public/vietnam_GettyImages-878931880_HR_WEB.jpg?w=1600&h=900" alt="hanoi">
    <div class="text">
      <a href="/?query=Hanoi&button="><h3>hanoi</h3></a>
    </div>
  </div>
  <div class="city">
    <img src="https://media.vogue.mx/photos/5e19fa7ba3810f0008d96d3e/3:2/w_3240,h_2160,c_limit/Lima-%20La%20Costa%20Verde.jpg" alt="lima">
    <div class="text">
      <a href="/?query=Lima&button="><h3>lima</h3></a>
    </div>
  </div>
  <div class="city">
    <img src="https://www.travelandleisure.com/thmb/LzWpzDihxjffaFmM9TZWCvm9VyY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/lisbon-portugal-LISBONTG0521-c933a0fb669647619fa580f6c602c4c8.jpg" alt="lisbon">
    <div class="text">
      <a href="/?query=Lisbon&button="><h3>lisbon</h3></a>
    </div>
  </div>
</div>
<footer>
  <div>
    <p>ABOUT</p>
    <p>CAREERS</p>

  </div>
  <div>
    <p>PRIVACY</p>
    <p>POLICY</p>


  </div>
  <div>
    <p>SUPPORT</p>
    <p>TERMS OF USE</p>
  </div>

</footer>


<style>
footer{
  display:flex;
  justify-content:center;
  border-top:1px solid #FF6600;
  width:80%;
  position: fixed;
   bottom: 0;
   right:10%;


}

footer p {
  color:#FF6600;
  margin-bottom:2px;
}
footer div{
  margin:0 20px;
  padding:10px;
  display: flex;
  flex-direction: column;
  align-items: center;
}
</style>


<%# <script>
  let searchBtn = document.querySelect(".search-icon-button")

  searchBtn.addEventListener

</script> %>

app/views/pages/profile.html.erb
<div class='main'>
  <div class='user-info'>
    <h1><%= current_user.first_name %></h1>
  </div>

  <div class='add-listing-form'>
    <div id='form' class='form'>
      <div id='exit-form'>
        <p>X</p>
      </div>
      <%= simple_form_for(@hostel) do |f| %>
        <%= f.input :name, class: 'input' %>
        <%= f.input :city, class: 'input' %>
        <%# <%= f.input :address, class: 'input' %>

        <%= f.input :address,
            input_html: {data: {address_autocomplete_target: "address"}, class:"d-none"},
            wrapper_html: {data: {controller: "address-autocomplete",
            address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
        %>
        <%= f.input :description, as: :string, class: 'input' %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit 'add listing', class: 'submit-btn' %>
      <% end %>
    </div>
  </div>

  <div class='user-listings'>
    <div class='listings'>
      <h3>Listings</h3>
      <a class='button' id='add-list-btn'>add a listing</a>
    </div>
    <ul>
      <% @hostels.each do |hostel| %>
        <li>
          <div class='hostel-info'>
            <%= link_to "#{hostel.name}", hostel_path(hostel), class: 'hostel-name' %>
            <p><%= hostel.city %></p>
          </div>
          <div class='buttons'>
            <div id='edit-btn' class='button'> <i class="fa-solid fa-pen"></i>
              <div class='edit-list-form'>
                <%= simple_form_for(@hostel) do |f| %>
                  <%= f.input :name %>
                  <%= f.input :city %>
                  <%= f.input :address %>
                  <%= f.input :description %>
                  <%= f.submit 'edit listing', class: 'submit-btn' %>
                <% end %>
              </div>
            </div>
            <%= link_to hostel_path(hostel), data: {turbo_method: :delete}, class: 'button' do %>
            <i class="fa-regular fa-trash-can"></i>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class='reservations'>
    <h3>Reservations</h3>
    <ul>
      <% current_user.reservations.each do |reservation| %>
        <% if reservation.end_date > Date.today %>
          <% @hostel = reservation.room.hostel %>
          <li>
            <div class='hostel-info'>
              <%= link_to "#{@hostel.name}", hostel_path(@hostel), class: 'hostel-name' %>
              <p><%= @hostel.city %></p>
            </div>
            <div class='res-dates'>
              <% nights = (reservation.end_date - reservation.start_date).to_s.split('/')[0] %>
              <p><strong>$<%= (reservation.room.price_per_night * nights.to_i) * reservation.amount_of_beds %></strong> to pay on arrival</p>
              <p><%= reservation.start_date.to_formatted_s(:long) %></p>
              <p>to <%= reservation.end_date.to_formatted_s(:long) %></p>
            </div>
            <div class='buttons'>
              <div id='edit-btn' class='button'> <i class="fa-solid fa-pen"></i>
                <div class='edit-res-form'>
                  <%= simple_form_for(reservation) do |f| %>
                    <%= f.input :start_date, as: :date, html5: true %>
                    <%= f.input :end_date, as: :date, html5: true %>
                    <%= f.input :amount_of_beds, collection: 1..reservation.room.number_of_beds %>
                    <%= f.submit "edit reservation", class: 'submit-btn' %>
                  <% end %>
                </div>
              </div>
              <%= link_to  reservation_path(reservation), data: {turbo_method: :delete}, class: 'button'  do%>
                <i class="fa-regular fa-trash-can"></i>
              <% end %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <h3>Past reservations</h3>
    <ul>
      <% current_user.reservations.each do |reservation| %>
        <% if reservation.end_date < Date.today %>
          <% @hostel = reservation.room.hostel %>
          <li>
            <div class='hostel-info'>
              <%= link_to "#{@hostel.name}", hostel_path(@hostel), class: 'hostel-name' %>
              <p><%= @hostel.city %></p>
            </div>
            <div class='res-dates'>
              <p><%= reservation.start_date.to_formatted_s(:long) %></p>
              <p>to <%= reservation.end_date.to_formatted_s(:long) %></p>
            </div>
            <div class='buttons'>
              <div id='review-btn' class='button'>leave a review
                <div class="add-review-form">
                  <%= simple_form_for([@hostel, @review]) do |f| %>
                      <%= f.input :content %>
                      <%= f.input :rating, collection: (1..5).to_a %>
                      <%= f.submit 'add review', class: 'submit-btn' %>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<script>
  const addBtn = document.getElementById('add-list-btn')
  const closeBtn = document.getElementById('exit-form')

  addBtn.addEventListener('click', (event) => {
    document.getElementById('form').style.display = "block";
  })

  closeBtn.addEventListener('click', (event) => {
    document.getElementById('form').style.display = "none";
  })
</script>